build: off

branches:
  only: [master]

# Don't run specs because sass-spec doesn't support Windows. They're also
# supposed to be platform-independent.
environment:
  matrix:
  #- {TASK: tests, NODE: false}
  - {TASK: tests, NODE: true}

install:
- choco install dart-sdk
- refreshenv
- pub get
- ps: >-
    If ($env:NODE -eq "true") {
      Install-Product node ''
      $env:SASS_MINIFY_JS = "false"
      pub run grinder npm_package
    }

# Don't run Node tests on Windows until dart-lang/sdk#30098 lands.
test_script:
- ps: >-
    If ($env:NODE -eq "true") {
      pub run test -p vm -t node -N "supports relative imports"
    } Else {
      pub run test -x node
    }
