name: sass_analysis
version: 0.0.0
description: Shared analysis options for Sass team packages.
homepage: https://github.com/sass/dart-sass/tree/master/analysis

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  lints: ^4.0.0
